name: Pylint

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  pylint:
    if: ${{ !github.event.pull_request.draft }}
    uses: EntityRisk/infrastructure/.github/workflows/project-pylint.yml@main
    with:
      python-version: '3.10'
    secrets: inherit
